### ISSUE TITLE
Remove cabal.project.local file from repo.

### ISSUE THREAD

**Issue by patrickt** [github/semantic#112]
This is the Wrong Thing to do. Our documentation should specify to run `cabal new-configure --disable-optimization semantic semantic-core`, which generates a `cabal.project.local` file, and we should remove and .gitignore it.

**Comment by robrix** [comment]
@patrickt: This doesn’t appear to be in the repo at all, and we furthermore ignore it. Can we close this out?

**Comment by patrickt** [comment]
Oh, lol! I thought we had it in the repo. What we _do_ need is instructions on how to generate one such that `optimizations: False`. I’ll close this and do it in another patch.
