### ISSUE TITLE
Use tasty + tasty-golden for parse-examples tests.

### ISSUE THREAD

**Issue by patrickt** [github/semantic#120]
These diffs are a prime example of golden testing: we want to match diff output exactly. If we use `tasty` as our prime test runner, we can use `tasty-golden` to set up a more accurate test of meaning (rather than just using `shouldBe` on a big string), and we’ll get pretty diff output without having to keep `hspec-expectations-pretty-diff` around (#116).

**Comment by robrix** [comment]
> golden testing

[TIL](https://ro-che.info/articles/2017-12-04-golden-tests).
