### ISSUE TITLE
Switch from Leancheck to Hedgehog.

### ISSUE THREAD

**Issue by patrickt** [github/semantic#122]
Leancheck is a lovely library, but it is not as ergonomic nor as rich in API as Hedgehog. We’re already using Hedgehog for `semantic-core`, might as well go all the way. This would enable us to get rid of that `Instances.hs` file that has like 125 orphan instances.

**Comment by robrix** [comment]
cf #69

**Comment by robrix** [comment]
I’d like to also suggest QuickCheck.

**Pros:**
- [`doctest`](https://hackage.haskell.org/package/doctest) supports it already (and relies on `Arbitrary` instances).
- It seems to enjoy better support for testing generated distributions (cf [_Building on developers’ intuitions to create effective property-based tests_](https://www.youtube.com/watch?v=NcJOiQlzlXQ) and the docs for e.g. `label` & `classify`).
- The [manual](http://www.cse.chalmers.se/~rjmh/QuickCheck/manual.html) is pretty excellent.

**Cons:**

- Shrinking has to be defined manually.
- `Arbitrary` is lawless.

**Comment by patrickt** [comment]
Compatibility with `doctest` is indeed a big win. I personally find the limitations of an `Arbitrary`-based approach very frustrating, but the docs are indeed good and we should definitely look into how the shrinking/generated distribution testing compares to QuickCheck.

One of the big advantages of #120 is that we can drop in tests from any test framework and they’ll DTRT, so we can mix and match as necessary.

**Comment by patrickt** [comment]
I’ve also found the Hedgehog docs to be excellent.

**Comment by robrix** [comment]
I’m reasonably convinced that Hedgehog is the way to go now. I just wish there were a doctest equivalent for Hedgehog, as I tend to go out of my way to avoid writing `Arbitrary` instances for doctests anyway!
