### ISSUE TITLE
Turn on warnings for tests.

### ISSUE THREAD

**Issue by patrickt** [github/semantic#127]
#120 adds `-Wunused-imports`; we should just apply all the relevant `ghc-options` (as specified in the `semantic:lib` component) in the `common` stanza so they’re shared between all targets.

**Comment by jhrcek** [comment]
@patrickt I will gladly take a stab at this.
Does this issue include fixing all the warnings given by the enabled warning options?

I quickly executed `cabal new-test` with the same warning options in `test-suite test` which are used in the library component, getting these results (summary):
```
grep '\[-W.*\]' -o --color  stderr | sort | uniq -c | sort -rn
    210 [-Wname-shadowing]
     32 [-Wunused-matches]
      7 [-Wmissing-export-lists]
      6 [-Wmissing-signatures]
      6 [-Wdodgy-imports]
      3 [-Wunused-top-binds]
      3 [-Wunused-imports]
      2 [-Wincomplete-uni-patterns]
      1 [-Wtype-defaults]
      1 [-Wredundant-constraints]
      1 [-Wincomplete-patterns]
```
.. so the general question is:
1. is there a code style guide? How do you prefer name shadowing to be resolved (e.g. some standardized suffix to variables like renaming `shadowedName` to `shadowedName'`?
2. what to do with unused matched? They I can e.g. replace

`Pattern var1 var2 unusedVar3 (unused@(unusedVar4,v5))`

with 

`Pattern var1 var2 _ ((_,v5))` replacing unused names with underscore (but losing some info about what names are involved

or just prefixing them with underscore 

`Pattern var1 var2 _unuseddVar3 (unused@(_unusedVar4,v5))`

**Comment by robrix** [comment]
@jhrcek thanks so much!

Yes, I think fixing warnings would be great—I think we might have `-Werror` on in CI.

One bit of good news, tho, we actually use `-fno-warn-name-shadowing` (not sure why that vs. `-Wno-warn-name-shadowing` tbh) so those 210 `-Wname-shadowing` warnings can be ignored 😊

I personally prefer using wildcards for unused matches, rather than underscore prefixes.

**Comment by jhrcek** [comment]
> not sure why that vs. -Wno-warn-name-shadowing tbh

In GHC user guide I found [this](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--fshow-warning-groups):

> To turn off any warning, simply give the corresponding -Wno-... option on the command line. For backwards compatibility with GHC versions prior to 8.0, all these warnings can still be controlled with -f(no-)warn-* instead of -W(no-)*.

So I'll switch to the `-Wno-name-shadowing` as I see this repo recommends 8.6.4

**Comment by robrix** [comment]
Great find, and thank you very much!

**Comment by patrickt** [comment]
@jhrcek Thanks for taking a look at this! You asked about our style guide—it can be found [here](https://github.com/github/semantic/blob/master/docs/coding-style.md).

**Comment by jhrcek** [comment]
Implemented in https://github.com/github/semantic/pull/149 and https://github.com/github/semantic/pull/157 so this can be probably closed.
