### ISSUE TITLE
Couldn't match expected type ‘GHC.Prim.Proxy# a0’ with actual type ‘Proxy (Enumerated Language)’ while 'cabal build'

### ISSUE THREAD

**Issue by Yuki-Minakami** [github/semantic#139]
My Env:
ubuntu 18.04
cabal 2.2
ghc: 8.6.4 without sandbox
----------------------
Preprocessing library for semantic-0.6.0.0..
Building library for semantic-0.6.0.0..
[ 71 of 180] Compiling Data.Language    ( src/Data/Language.hs, dist/build/Data/Language.o )

src/Data/Language.hs:116:26: error:
    • Couldn't match expected type ‘GHC.Prim.Proxy# a0’
                  with actual type ‘Proxy (Enumerated Language)’
    • In the first argument of ‘primType’, namely
        ‘(Proxy @(Enumerated Language))’
      In the expression: primType (Proxy @(Enumerated Language))
      In an equation for ‘primType’:
          primType _ = primType (Proxy @(Enumerated Language))
    |
116 |   primType _ = primType (Proxy @(Enumerated Language))
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[153 of 180] Compiling Semantic.Api.V1.CodeAnalysisPB ( src/Semantic/Api/V1/CodeAnalysisPB.hs, dist/build/Semantic/Api/V1/CodeAnalysisPB.o )

src/Semantic/Api/V1/CodeAnalysisPB.hs:1348:33: error:
    Not in scope: type constructor or class ‘Proto3.PrimitiveEnum’
    Perhaps you meant ‘Proto3.Primitive’ (imported from Proto3.Suite)
    Module ‘Proto3.Suite’ does not export ‘PrimitiveEnum’.
     |
1348 |   deriving Proto3.Primitive via Proto3.PrimitiveEnum ChangeType
     |                                 ^^^^^^^^^^^^^^^^^^^^

**Comment by Yuki-Minakami** [comment]
The second one seems issue with Proto3.Suit, 
does it relate to the upgrade of that ?

**Comment by patrickt** [comment]
Hmm, it looks like this isn’t using the correct `proto3-suite`. I think it may be due to too old of a version of `cabal-install`. @Yuki-Minakami, can you try upgrading (with `ghcup`) to `cabal-install` version 2.4?

**Comment by robrix** [comment]
(cf #111?)

**Comment by robrix** [comment]
@patrickt: Since we kind of depend on the `source-repository-package` stanzas for correct building, should we set the cabal file’s version to 2.4?

**Comment by Yuki-Minakami** [comment]
@patrickt 
I removed my cabal and installed cabal 2.4.1 and met same error while 'cabal new-build',

but this time the error about **proto3.suite** has gone.

**Comment by bryanweast** [comment]
I feel like I'm sitting in the twilight zone. Cobol and Cabal's weird similarities and the creepy undertones to the language kinda fascinate me.

**Comment by bryanweast** [comment]
Am I like going crazy or is there a secret language behind Cobol and Smalltalk. It looks like a way of communicating or possibly the code of the human mind?

**Comment by patrickt** [comment]
@Yuki-Minakami Could you please paste complete console output for `cabal new-build` in a Gist or in this issue?

**Comment by Yuki-Minakami** [comment]
@patrickt  
thanks for your commit.
it works fine after I update source code.
