### ISSUE TITLE
Tag computation only supports à la carte ASTs

### ISSUE THREAD

**Issue by robrix** [github/semantic#146]
Right now we can only compute symbols for à la carte ASTs, but we’re starting to migrate to precise ASTs (e.g. the TH-generated ASTs @aymannadeem has developed in `haskell-tree-sitter`). Therefore we’ll need to be able to compute them for the latter as well.

Ideally this should be generic; and in that case it’ll probably depend on https://github.com/tree-sitter/haskell-tree-sitter/issues/135 to avoid orphan instances.

Note that this will make it easier to support new languages since symbol support won’t require any sort of `Assignment`.

**Comment by aymannadeem** [comment]
Just to add clarity (for no one but myself), the use of "symbols" here refers to how the jump to def symbols are computed (not the `SymbolMatching`/`nodeSymbol` or `mkSymbolDatatype` symbols).

**Comment by robrix** [comment]
Confusing things further, I actually meant _tags_, not symbols; it’s just that the `Tags.Tagging` stuff is called from `Semantic.Api.Symbols` :joy:
