### ISSUE TITLE
"semantic graph xx.js" pending without any output 

### ISSUE THREAD

**Issue by Yuki-Minakami** [github/semantic#150]
Finally I got close to the goal~~
Now I had a simple index.js to test semantic graph.

when i ran `cabal new-run semantic -- graph index.js`
it printed  "up to date" and got pending there.
![捕获](https://user-images.githubusercontent.com/11377230/59516086-24f8e800-8ef3-11e9-96c4-dd0eeb634bc5.PNG)

Could I found some logs anywhere to figure out what happened behind?

**PS; All command works fine with .py code.**

**Comment by tclem** [comment]
`graph` currently iterates the entire directory tree starting in the current directory. You can change this by passing `--root DIR` (see all options by running `cabal new-run semantic -- graph --help`) or make and `cd` into a temporary directory, put `index.js` in there and try it again.

You can change the log level by passing `--log-level debug` (again see top level `semantic --help`).

**Comment by Yuki-Minakami** [comment]
@tclem 
It really helps!!
