### ISSUE TITLE
How to get the exact definition of an usage

### ISSUE THREAD

**Issue by zfy0701** [github/semantic#164]
Hi,

If I have a piece of code like 
```
parts[parts.length - 2].startsWith('@')
```

looks like currently the `parse --symbol` will just give you information like

```
        {
          "symbol": "startsWith",
          "kind": "Call",
          "line": "parts[parts.length - 2].startsWith('@')",
          "span": {
            "start": {
              "line": 272,
              "column": 54
            },
            "end": {
              "line": 272,
              "column": 93
            }
          }
        },
```

which is really usefully, but theoretically we should be able to get detail information like fully qualified name like `String.startsWith`, otherwise it's might have may `startWith` method in different classes

Is there already a way to get that information now? Or does semantic already do that internally but just not exposed right now

**Comment by patrickt** [comment]
Hi! `parse --symbols` is a very simple tagging system: it reflects only the AST nodes. The `graph` command, which performs nontrivial analysis, is a more relevant subcommand to what you want. Something like `semantic graph --packages --calls --json` will probably give you the information you need (though, `semantic` being alpha software and all, it might not—if not, please let us know what’s missing and we’ll make sure it’s covered in an issue).

**Comment by zfy0701** [comment]
thanks for the info, so I create a project with following `package.json`:
```
{
  "name": "semantic-test",
  "version": "0.0.0",
  "devDependencies": {
    "@types/node": "10.12.18"
  }
}
```
and one `src/app.ts`:
```
process.exit();
```

the call graph I have is:
```
digraph
{
  "src (Package)" [style="dashed" shape="box"]
  "Semantic.Analysis (Module)" [style="dotted, rounded" shape="box"]
  "app.ts (Module)" [style="dotted, rounded" shape="box"]
  "app.ts::process (Variable [2, 1] - [2, 8])" [label="process (Variable)" tooltip="[2, 1] - [2, 8]" style="rounded" shape="box"]
  "app.ts::process.exit (Variable [2, 1] - [2, 13])" [label="process.exit (Variable)" tooltip="[2, 1] - [2, 13]" style="rounded" shape="box"]
  "src (Package)" -> "Semantic.Analysis (Module)" [len="5.0" style="dashed"]
  "src (Package)" -> "app.ts (Module)" [len="5.0" style="dashed"]
  "app.ts (Module)" -> "app.ts::process (Variable [2, 1] - [2, 8])" [len="2.0" color="green" label="calls"]
  "app.ts (Module)" -> "app.ts::process.exit (Variable [2, 1] - [2, 13])" [len="2.0" color="green" label="calls"]
}
```

which is not exactly what I expected, e.g. the `exit` call should resolved to the following:
![image](https://user-images.githubusercontent.com/1646270/59645868-067c3200-9129-11e9-91bc-8ab50516edaf.png)
 
I tried to use another file by manually tagging the type
```
const process: NodeJS.Process;
process.exit();
```
the call graph is still very similar.

**Comment by patrickt** [comment]
If I understand you right, you’re trying to resolve that `exit` call to the `Process` library provided by Node, correct? We don’t currently gather information from the standard library—this is an unfortunate flaw that we’re aware of. We’ve done [some work](https://github.com/github/semantic/blob/master/src/Data/Abstract/Evaluatable.hs#L168-L176) on providing standard library primitives during concrete evaluation, but we don’t have a solution for this during abstract interpretation (which `graph` entails). 

We’d like to fix this, but the best way to do it isn’t yet clear. There are a number of suboptimal solutions: we could re-parse and re-graph the entire standard library of a given language before we start graphing user code, which would be prohibitively slow; we could hardcode details of each supported language’s stdlib into Semantic itself, which is bad for maintainability; we could try to do the work in advance and cache it, but getting caching right is really hard. And whatever method we choose needs to scale to all of our core languages and languages not yet integrated with Semantic.

I’ve filed the request for stdlib support in `semantic --graph` as #165. If you have any more questions, please drop them in this thread!

**Comment by zfy0701** [comment]
Yes. I'm trying to resolve that to Node library. I just notice that we had the following error:
`
[20:16:25]  WARN /Users/fuyaoz/src/semantic-test/node_modules/@types/node/index.d.ts:1:1-2294:44: error: expected end of input nodes, but got ParseError
1: // Type definitions for Node.js 10.12
`
when analyzing this file:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts

after realizing it's a parsing problem, I tried a two file project without any dependencies:
B.ts:
```
export class B {
  public foo() {}
}
```

app:ts
```
import { B } from './B';

class C {
  public foo() {}
}

const b: B = new B();
b.foo();
```

so I tried to see how I can get the call site `b.foo` resolved to `B.foo` instead of `C.foo`.  so I run
`semantic graph --packages --calls  src/app.ts` 

```
digraph
{
  "src (Package)" [style="dashed" shape="box"]
  "B.ts (Module)" [style="dotted, rounded" shape="box"]
  "Semantic.Analysis (Module)" [style="dotted, rounded" shape="box"]
  "app.ts (Module)" [style="dotted, rounded" shape="box"]
  "app.ts::b (Variable [13, 1] - [13, 2])" [label="b (Variable)" tooltip="[13, 1] - [13, 2]" style="rounded" shape="box"]
  "app.ts::b.foo (Variable [13, 1] - [13, 6])" [label="b.foo (Variable)" tooltip="[13, 1] - [13, 6]" style="rounded" shape="box"]
  "B.ts::foo (Method [2, 3] - [2, 18])" [label="foo (Method)" tooltip="[2, 3] - [2, 18]" style="rounded" shape="box"]
  "app.ts::foo (Method [9, 3] - [9, 18])" [label="foo (Method)" tooltip="[9, 3] - [9, 18]" style="rounded" shape="box"]
  "src (Package)" -> "B.ts (Module)" [len="5.0" style="dashed"]
  "src (Package)" -> "Semantic.Analysis (Module)" [len="5.0" style="dashed"]
  "src (Package)" -> "app.ts (Module)" [len="5.0" style="dashed"]
  "B.ts (Module)" -> "B.ts::foo (Method [2, 3] - [2, 18])" [len="2.0" color="red" label="defines"]
  "app.ts (Module)" -> "B.ts (Module)" [len="5.0" label="imports"]
  "app.ts (Module)" -> "app.ts::b (Variable [13, 1] - [13, 2])" [len="2.0" color="green" label="calls"]
  "app.ts (Module)" -> "app.ts::b.foo (Variable [13, 1] - [13, 6])" [len="2.0" color="green" label="calls"]
  "app.ts (Module)" -> "app.ts::foo (Method [9, 3] - [9, 18])" [len="2.0" color="red" label="defines"]
}
```

it seems the line relevant is 
`
  "app.ts (Module)" -> "app.ts::b.foo (Variable [13, 1] - [13, 6])" [len="2.0" color="green" label="calls"]
`
but not very clean how this resolve to `C.foo`
