### ISSUE TITLE
Why Haskell: Lazy Evaluation

### ISSUE THREAD

**Issue by bitc** [github/semantic#166]
From the document [why-haskell.md](https://github.com/github/semantic/blob/master/docs/why-haskell.md):

> Lazy evaluation isn't always what you want and can have performance problems and make some debugging activities incredibly frustrating.

The above sentiment about Haskell is often repeated, and it is my opinion that it is a complete myth (and to a certain extend FUD). It reminds me of the fear and objections people had regarding garbage collection, before it finally broke into the mainstream and became widely accepted ("GC can lead to intractable performance problems").

I have worked with Haskell for a long time, and on only one occasion did I encounter a surprising performance problem that turned out to be because of lazy evaluation, and solving that was not difficult and did not take much time. My point isn't to claim that lazy evaluation is strictly superior to strict evaluation, but it just irritates me whenever I see lazy evaluation baselessly painted as a horrible scary bogeyman that too often frightens people away from Haskell. So to see the claim repeated by the authors of this high-quality Haskell project is disappointing.

I would be very interested to hear from this project's developers about specific examples of how lazy evaluation caused difficulties or problems during the development of this project. If there are genuine issues then it would be a great help to the community so that we can try to address them.

Thank you

**Comment by patrickt** [comment]
Hi there! That document speaks to our experience, no more, and we don’t claim it as an objective source of truth—as such, we won’t be modifying this choice of words. Non-strict evaluation is wonderful and we’re all _huge_ fans of the programming style it enables, but we’ve also needed to take measures (turning on `-XStrictData`, investing efforts in `fused-effects`’s constant-space Writer effect, educating new Haskellers to `foldl’` and never `foldl`) to avoid accumulating thunks. Problems like the above rarely happen in more conventional programming languages, and mentioning this doesn’t qualify as FUD. We’ll be happy to be in touch on the GHC issue tracker then we have concrete suggestions to improve the experience of non-strict programming.
