### ISSUE TITLE
Document the changes to the process for increasing language support due to precise ASTs

### ISSUE THREAD

**Issue by robrix** [github/semantic#173]
We’re making it easier to add support for new languages & improve support for existing languages via the generation of precise ASTs in the per-language `tree-sitter-*` packages (cf https://github.com/tree-sitter/haskell-tree-sitter/pull/144). We should document the changes to the process as they become available.

**Comment by robrix** [comment]
cc @aymannadeem who’s spearheading the precise AST derivation & un-marshalling work.

**Comment by robrix** [comment]
I’m of two minds as to whether we should document what is involved in migrating one of our _existing_ supported languages from the old-style `Assignment` &c. flow to the new-style precise AST flow; I think we should instead add support for a new language using the new flow as an example, and then just migrate the old ones over ourselves as we develop support for existing features (e.g. diffing, tagging) over them.

**Comment by aymannadeem** [comment]
Thanks, @robrix! Like I've said in earlier discussions, I have bits of this written up and intend to [create a PR to the docs](https://github.com/github/semantic/blob/master/docs/adding-new-languages.md) once it's more fully in place. 😸 

I agree with your proposal to (1) migrate existing languages to the new system ourselves and (2) change the docs to reflect the new system. 👍

**Comment by KevOrr** [comment]
Sorry if this is off-topic for this issue, but is there any estimate (even a very rough one) on when we might have precise ASTs?

**Comment by dcreager** [comment]
Hi @KevOrr!  It might look like this is on the back burner since there haven't been any comments in over a month, but a couple of people on the team are actively working on this and we hope to have something ready soon.  No concrete timeline that I can commit, too, though.  Thanks for your patience!
