### ISSUE TITLE
Python lambdas should not use Evaluatable Function

### ISSUE THREAD

**Issue by joshvera** [github/semantic#182]
Python lambdas do not close over their arguments so we should interpret them with a different `Evaluatable` instance than `Evaluatable Function`.

See https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result.

**Comment by Patil2099** [comment]
@joshvera  Can I Work on this Issue? Where do I have to make changes?
Thanks
