### ISSUE TITLE
[question] Are node types enumerated anywhere?

### ISSUE THREAD

**Issue by KevOrr** [github/semantic#183]
Hi, I'm trying to ingest the JSON output from `semantic parse --json`, and I've been looking through the docs and source to see if there is a global list of predefined AST node types (the value that corresponds to a `term` key), and/or language-specific node types.

I've found [src/Data/Syntax/](https://github.com/github/semantic/tree/master/src/Data/Syntax), and it seems that just about every new type that derives `Diffable, Eq, Foldable, Functor, Generic1, Hashable1, Ord, Show, Traversable, FreeVariables1, Declarations1, ToJSONFields1, NFData1` (or some subset) is a possible node type. In addition, each language can create new kinds of nodes. Is there any documentation that lays out all the possible kinds of nodes, so we can be fairly sure that we are exhaustively matching all kinds of nodes?

**Comment by joshvera** [comment]
@KevOrr Each language's syntax is defined by a sum type when we assign a tree-sitter grammar to Haskell data types. Here's Ruby's [syntax sum type](https://github.com/github/semantic/blob/master/src/Language/Ruby/Assignment.hs#L42) for example.

That should suffice if you're trying to exhaustively match a particular language's syntax. If you're trying to match every language we support, you'll have to match the product of those language's syntax types.

**Comment by KevOrr** [comment]
Ah, perfect, thank you
