### ISSUE TITLE
String concatenation/concat-assignment with `.` is assigned incorrectly

### ISSUE THREAD

**Issue by KevOrr** [github/semantic#186]
In [src/Language/PHP/Assignment.hs:269](https://github.com/github/semantic/blob/b4792db2528153d9d471877d6f35693e76f5dd28/src/Language/PHP/Assignment.hs#L269), both an expression like `"hello" . " world"` (concatenation) and one like `1 * 2` (multiplication) will be tagged as a `Times` term. Is this on purpose?

https://github.com/github/semantic/blob/b4792db2528153d9d471877d6f35693e76f5dd28/src/Language/PHP/Assignment.hs#L245-L273

(See #188) ~~Also in that file, on [line 258](https://github.com/github/semantic/blob/b4792db2528153d9d471877d6f35693e76f5dd28/src/Language/PHP/Assignment.hs#L258), `$i !== $j` will (approximately) parse as `(Not (Equal (Identifier i) (Identifier j)))`. According to https://www.php.net/manual/en/language.operators.comparison.php, `!==` means "not identical". It seems that semantic denotes "identical" by `StrictEqual`, given [line 257](https://github.com/github/semantic/blob/b4792db2528153d9d471877d6f35693e76f5dd28/src/Language/PHP/Assignment.hs#L257). Should it instead parse as `(Not (StrictEqual (Identifier i) (Identifier j)))`?~~

**Comment by joshvera** [comment]
@KevOrr That sounds about right! Those both seem like bugs to me, I don't have time to take a look right now but it should be an easy fix.

**Comment by patrickt** [comment]
I’m peeling this off into two separate bugs.

**Comment by KevOrr** [comment]
Same thing with augmented assignment. A statement like `$i .= "a"` will be assigned `(Assignment ... (Times (VariableName (Identifier)) (TextElement)))`

https://github.com/github/semantic/blob/b4792db2528153d9d471877d6f35693e76f5dd28/src/Language/PHP/Assignment.hs#L228-L243

**Comment by patrickt** [comment]
Changed the title to reflect the above. Anyone who wants to fix these can and should; the patches should be pretty minimal.

**Comment by KevOrr** [comment]
@patrickt a new tag needs to be created right? Is it better to add it to Language.PHP.Syntax or Data.Syntax.Expression?

**Comment by joshvera** [comment]
@KevOrr I’d go with `Language.PHP.Syntax` unless it’s a widely available piece of syntax.

**Comment by patrickt** [comment]
@KevOrr There’s a `StrictEqual` node in `Data.Syntax.Expression`.
