### ISSUE TITLE
If/elif/else blocks are not assigned correctly

### ISSUE THREAD

**Issue by KevOrr** [github/semantic#187]
I believe Python if/elif/else statements are being parsed incorrectly. E.g. (sample a)

```python
if a:
    x = 1
elif b:
    x = 2
else:
    x = 3
```

<details>
<summary>parses as (minus source info) ...</summary>
<pre>
<code>
{
  "term": "Statements",
  "statements": [
    {
      "term": "If",
      "ifCondition": {
        "term": "Identifier",
        "name": "a"
      },
      "ifElseBody": {
        "children": [
          {
            "term": "If",
            "ifCondition": {
              "term": "Identifier",
              "name": "b"
            },
            "ifElseBody": {
              "children": []
            },
            "ifThenBody": {
              "term": "Assignment",
              "assignmentContext": [],
              "assignmentTarget": {
                "term": "Identifier",
                "name": "x"
              },
              "assignmentValue": {
                "term": "Integer",
                "integerContent": "2"
              }
            }
          },
          {
            "term": "Assignment",
            "assignmentContext": [],
            "assignmentTarget": {
              "term": "Identifier",
              "name": "x"
            },
            "assignmentValue": {
              "term": "Integer",
              "integerContent": "3"
            }
          }
        ]
      },
      "ifThenBody": {
        "term": "Assignment",
        "assignmentContext": [],
        "assignmentTarget": {
          "term": "Identifier",
          "name": "x"
        },
        "assignmentValue": {
          "term": "Integer",
          "integerContent": "1"
        }
      }
    }
  ]
}
</code>
</pre>
</details>

Note how there are two children under `.statements[0].ifElseBody.children`. This seems to indicate that the implicit `if b: x = 2` statement, as well as `x = 3` are both children of the `ifElseBody`. Indeed, the following snippet (sample b) produces the same parse tree:

```python
if a:
    x = 1
else:
    if b:
        x = 2
    x = 3
```

The `x = 3` would need to be inside an `else:` block. Incidentally, the following snippet (sample c):

```python
if a:
    x = 1
else:
    if b:
        x = 2
    else:
        x = 3
```

<details>
<summary>produces the correct parse tree ...</summary>
<pre>
<code>
{
  "term": "Statements",
  "statements": [
    {
      "term": "If",
      "ifCondition": {
        "term": "Identifier",
        "name": "a"
      },
      "ifElseBody": {
        "term": "If",
        "ifCondition": {
          "term": "Identifier",
          "name": "b"
        },
        "ifElseBody": {
          "term": "Assignment",
          "assignmentContext": [],
          "assignmentTarget": {
            "term": "Identifier",
            "name": "x"
          },
          "assignmentValue": {
            "term": "Integer",
            "integerContent": "3"
          }
        },
        "ifThenBody": {
          "term": "Assignment",
          "assignmentContext": [],
          "assignmentTarget": {
            "term": "Identifier",
            "name": "x"
          },
          "assignmentValue": {
            "term": "Integer",
            "integerContent": "2"
          }
        }
      },
      "ifThenBody": {
        "term": "Assignment",
        "assignmentContext": [],
        "assignmentTarget": {
          "term": "Identifier",
          "name": "x"
        },
        "assignmentValue": {
          "term": "Integer",
          "integerContent": "1"
        }
      }
    }
  ]
}
</code>
</pre>

**Comment by Patil2099** [comment]
@patrickt Can I work on this issue? Also, Which File I have to correct?

**Comment by robrix** [comment]
@Patil2099: Absolutely! It’s most likely occurring in the `Language.Python.Assignment` module: https://github.com/github/semantic/blob/master/src/Language/Python/Assignment.hs

**Comment by KevOrr** [comment]
I'm not too familiar with the Semantic's parser combinators, but my intuition says that this line might be what's causing both the `elif` and `else` to be assigned as `ifElseBody` children:

https://github.com/github/semantic/blob/7fc70fdd595582c2901a66af20529cb02efe4370/src/Language/Python/Assignment.hs#L473

**Comment by patrickt** [comment]
This code path no longer exists; the precise ASTs should handle it correctly.
