### ISSUE TITLE
Call graph vertices are not properly tagged with their unique ID

### ISSUE THREAD

**Issue by cyw3** [github/semantic#189]
What do source and target mean?

> ./semantic graph --calls --json demo:python

![image](https://user-images.githubusercontent.com/11549103/60327339-254ab600-99be-11e9-87ef-17e8e7a7c543.png)

![image](https://user-images.githubusercontent.com/11549103/60327190-d4d35880-99bd-11e9-9580-8fb293d0a4b2.png)

**Comment by patrickt** [comment]
Hi there! These unique identifier numbers (which is what they are) are meant to correspond to vertices, but we’re not including these numbers in the vertices’ JSON objects. Good catch—we’ll fix this soon.

**Comment by patrickt** [comment]
@cyw3 We’ve fixed the issue you identified: vertices’ identifiers are now preserved in the vertex hash. Please feel free to comment here or open a new issue if you have more questions.
