### ISSUE TITLE
Allow specifying language via flag

### ISSUE THREAD

**Issue by dkasak** [github/semantic#194]
Would you consider supporting a `--language` flag for the `diff` subcommand, similar to the one in `graph`? I know of the `FILE:LANGUAGE` syntax, but this sometimes clashes with colons in filenames and has to be specified for each file separately.

**Comment by robrix** [comment]
Great idea 👍

**Comment by dkasak** [comment]
I just realized I misspelled `parse` as `diff` in the title :grin: But I guess it would be a good idea to support it in all subcommands.

**Comment by robrix** [comment]
Agreed! 😊
