### ISSUE TITLE
Get line number and file info in call graph

### ISSUE THREAD

**Issue by kcmannem** [github/semantic#210]
I really liked the jump-to functionality GitHub added recently. I learned that its build using this repository so I though I'd play around with it. 

I'm wondering if there is a way to get line numbers and filenames from the call graph. That info might already be there, I might just not know how to read this syntax. I was going to use this to see if I could build my own primitive jump to extension for my code editor. 

Thanks.

**Comment by robrix** [comment]
I think you’re looking for `semantic parse --symbols`, e.g.:

<details>
<summary>Example output</summary>
<pre><code>$ cabal new-run -v0 exe:semantic -- parse --symbols test/fixtures/go/corpus/function-declarations.A.go | jq
{
  "files": [
    {
      "path": "test/fixtures/go/corpus/function-declarations.A.go",
      "language": "Go",
      "symbols": [
        {
          "symbol": "main",
          "kind": "Function",
          "line": "func main()",
          "span": {
            "start": {
              "line": 3,
              "column": 1
            },
            "end": {
              "line": 3,
              "column": 38
            }
          }
        },
        {
          "symbol": "f1",
          "kind": "Function",
          "line": "func f1()",
          "span": {
            "start": {
              "line": 4,
              "column": 1
            },
            "end": {
              "line": 4,
              "column": 38
            }
          }
        },
        {
          "symbol": "f2",
          "kind": "Function",
          "line": "func f2(a int, b, c, d string) int",
          "span": {
            "start": {
              "line": 5,
              "column": 1
            },
            "end": {
              "line": 5,
              "column": 38
            }
          }
        },
        {
          "symbol": "f2",
          "kind": "Function",
          "line": "func f2() (int, error)",
          "span": {
            "start": {
              "line": 6,
              "column": 1
            },
            "end": {
              "line": 6,
              "column": 38
            }
          }
        },
        {
          "symbol": "f2",
          "kind": "Function",
          "line": "func f2() (result int, err error)",
          "span": {
            "start": {
              "line": 7,
              "column": 1
            },
            "end": {
              "line": 7,
              "column": 38
            }
          }
        },
        {
          "symbol": "lockedOSThread",
          "kind": "Function",
          "line": "func lockedOSThread() bool",
          "span": {
            "start": {
              "line": 8,
              "column": 1
            },
            "end": {
              "line": 8,
              "column": 27
            }
          }
        },
        {
          "symbol": "getcontext",
          "kind": "Function",
          "line": "func getcontext(c *u) /* int32 */",
          "span": {
            "start": {
              "line": 9,
              "column": 1
            },
            "end": {
              "line": 9,
              "column": 37
            }
          }
        }
      ]
    }
  ]
}</code></pre>
</details>

That sounds like a fun project; enjoy!
