### ISSUE TITLE
Export particular high-level functions as a library

### ISSUE THREAD

**Issue by ch3rn0v** [github/semantic#218]
Hello! I wonder whether you plan to expose this project as a library, besides just a cli tool.
In particular, I'm interested in parsing files to ASTs (for which the function `parse` from src/Semantic/Task.hs seems responsible).

I found this package https://hackage.haskell.org/package/semantic , maybe it could be updated to export high-level functions to parse files into ASTs, generate call-graphs, etc?

Thank you!

**Comment by patrickt** [comment]
Hi! Yes, we are planning to release Semantic both as a command line tool and as a library. We’re tracking it in this issue: https://github.com/github/semantic/issues/16
