### ISSUE TITLE
Update to GHC 8.8

### ISSUE THREAD

**Issue by patrickt** [github/semantic#236]
Now that [GHC 8.8.1](https://www.haskell.org/ghc/blog/20190825-ghc-8.8.1-released.html) is released, we should consider upgrading. We may need to wait for our various dependencies to undergo their required bumps.

**Comment by robrix** [comment]
cf https://github.com/joshvera/proto3-suite/pull/33, blocked on https://github.com/ekmett/lens/issues/845

**Comment by patrickt** [comment]
Since we no longer use proto3-suite, we don’t need to worry about that one, but we do need to wait for proto-lens to loosen its base dependency: https://github.com/google/proto-lens/issues/341

**Comment by XVilka** [comment]
Homebrew now has 8.8.1, along with some other distributions:
https://repology.org/project/ghc/versions
