### ISSUE TITLE
JSX parse error with multi-line attribute

### ISSUE THREAD

**Issue by UltimateBeaver** [github/semantic#237]
Semantic team,

First of all, thank you very much for open sourcing this awesome tool! When I was parsing the react project with semantic CLI, I got a parse error for the following file: https://github.com/facebook/react/blob/master/fixtures/dom/src/components/fixtures/selection-events/index.js

Here is the error message when I invoke the CLI with the `--json` option:

```
[19:54:07]  WARN index.jsx:1:1-10:20: error: expected end of input nodes, but got ParseError
1: import FixtureSet from '../../FixtureSet';
   ^...

 task=parse github_request_id=- github_is_public=False path=index.jsx language=JSX
{"trees":[{"tree":{"term":"Error","errorActual":"ParseError","errorCallStack":[{"startLine":216,"module":"Language.TSX.Assignment","package":"semantic-0.6.0.0-inplace","site":"parseError","file":"src/Language/TSX/Assignment.hs","startColumn":119,"endColumn":129}],"errorChildren":[],"errorExpected":[],"sourceRange":[0,324],"sourceSpan":{"start":[1,1],"end":[10,20]}},"path":"index.jsx","language":"JSX"}]}
```

After tweaking the original source code a little bit, I found the problem lies in the multi-line attribute spans line 11 - 13. If I remove line 12 - 13, the following code would parse without an error:

```javascript
import FixtureSet from '../../FixtureSet';
import ReorderedInputsTestCase from './ReorderedInputsTestCase';
import OnSelectEventTestCase from './OnSelectEventTestCase';
const React = window.React;

export default function SelectionEvents() {
  return (
    <FixtureSet
      title="Selection Restoration"
      description="selection state before commits and then restoring it afterwards.">
      <ReorderedInputsTestCase />
      <OnSelectEventTestCase />
    </FixtureSet>
  );
}
```

Please let me know if you need any other info. Any help would be greatly appreciated, thanks in advance!

**Comment by patrickt** [comment]
Thank you for the detailed bug report! This looks to me like a `tree-sitter-tsx` bug; I’m transferring it over there.

**Comment by patrickt** [comment]
This lives over here now: https://github.com/tree-sitter/tree-sitter-typescript/issues/74

**Comment by maxbrunsfeld** [comment]
This code parses fine with `tree_sitter_tsx` now. It may already be fixed in Semantic since we've recently upgraded `tree-sitter-typescript`. If not, maybe we need to upgrade again?

**Comment by patrickt** [comment]
Tested this and it parses without error.
