### ISSUE TITLE
Can the parse timeout be configured?

### ISSUE THREAD

**Issue by defreez** [github/semantic#240]
When I try to parse files that are large (e.g. 7k lines of JS), I receive the following error after a few seconds:

~~~
time=2019-09-07T21:18:01Z+0000 msg="assignment timeout" level=Error task="assign" github_request_id="-" github_is_public="False" path="<filtered>" language="JavaScript" app="semantic" pid="787" hostname="2c984c056e4b" sha="development"
{
    "trees": [
        {
            "language": "JavaScript",
            "path": "/tmp/tmpdi96wjq5.js",
            "error": "AssignmentTimedOut"
        }
    ]
}
~~~

This is with the `sha_c1486db42dcbcc0a7748fc759017ab8d30d0f2d1` docker image.

Is there a way to adjust this timeout? Thanks!

**Comment by tclem** [comment]
Yes! There are a couple of different timeouts that are configurable and here's where most [configuration is tracked](https://github.com/github/semantic/blob/a9365c667c5dc92c0965fa5956f2b0ee7c344c59/src/Semantic/Config.hs).

The timeout from the error message you posted is controlled with the `SEMANTIC_ASSIGNMENT_TIMEOUT` environment variable (it's in milliseconds) so you could do something like this to bump the timeout from 4 to 10 seconds:

```
$ SEMANTIC_ASSIGNMENT_TIMEOUT=10000 semantic parse /tmp/tmpdi96wjq5.js
```

**Comment by defreez** [comment]
Works like a charm, thank you so much!
