### ISSUE TITLE
handle language server protocol( to have OCaml support.)

### ISSUE THREAD

**Issue by Et7f3** [github/semantic#244]
Hy,
[reason-language-server](https://github.com/jaredly/reason-language-server) implement language server protocol. Rls handle jump to definition for ReasonML/OCaml and it is widely used in many IDE. Does semantic will support lsp so we can add ReasonML/OCaml support.

**Comment by robrix** [comment]
LSP doesn’t provide enough information for us to use it as an input source, unfortunately.

**Comment by patrickt** [comment]
We have an issue tracking native OCaml support [here](https://github.com/github/semantic/issues/138).

**Comment by Et7f3** [comment]
@jaredly can you provide mode information in README to enable goto support on github ?
