### ISSUE TITLE
`cabal new-test` not working on a clean checkout

### ISSUE THREAD

**Issue by exterm** [github/semantic#249]
Hi,

I am trying to follow the instructions from the README, but `cabal new-test` yields

```
Resolving dependencies...
cabal: Cannot test the package semantic-0.7.0.0 because none of the components
are available to build: the test suite 'test' and the test suite
'parse-examples' are not available because the solver did not find a plan that
included the test suites. Force the solver to enable this for all packages by
adding the line 'tests: True' to the 'cabal.project.local' file.
```

I don't know how this is _supposed_ to work, but I would guess that this is unexpected? `cabal new-run semantic -- --help` works fine.

This is on an up-to date 2015 MacBook Pro.

**Comment by robrix** [comment]
Definitely unexpected, unless maybe you’d done a `cabal new-configure --disable-tests` previously in the package? Tho even then I’d be surprised that `new-test` would be bothered about that.

What does `cabal --version` have to say for itself?

**Comment by robrix** [comment]
> Tho even then I’d be surprised that `new-test` would be bothered about that.

I just tried `cabal new-configure --disable-tests` followed by `cabal new-test` and I am indeed surprised.

I think this is therefore a `cabal` thing rather than a `semantic` thing, and that your best bet is one of:

- `cabal new-test --enable-tests`,
- `cabal new-configure --enable-tests ; cabal new-test`, or
- remove anything along the lines of `tests: False` from `cabal.project.local` or possibly even your user cabal conf file & then `cabal new-test`

**Comment by robrix** [comment]
(removed the `bug` label for now because while this is clearly not the behaviour you desired, I don’t currently believe it to be a bug in `semantic` itself)

**Comment by exterm** [comment]
I did not execute `cabal new-configure --disable-tests`, I just followed the [steps from the README](cabal new-configure --disable-tests ) to the letter 🤷‍♂ 

```
≫ cabal --version
cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library
```

I _think_ `cabal new-test --enable-tests` mostly works (it gives me a metric ton of output), but it ends with 

```
parse-examples: tmp/haskell-tree-sitter/languages/python/vendor/tree-sitter-python/script/known_failures.txt: openBinaryFile: does not exist (No such file or directory)
Test suite parse-examples: FAIL
Test suite logged to:
/Users/philipmueller/src/github.com/github/semantic/dist-newstyle/build/x86_64-osx/ghc-8.6.5/semantic-0.7.0.0/t/parse-examples/test/semantic-0.7.0.0-parse-examples.log
0 of 1 test suites (0 of 1 test cases) passed.
cabal: Tests failed for test:parse-examples from semantic-0.7.0.0.
```

**Comment by exterm** [comment]
Thank you for looking into this 🙏

**Comment by robrix** [comment]
Could you post the test suite output please? Looks like it was written into `/Users/philipmueller/src/github.com/github/semantic/dist-newstyle/build/x86_64-osx/ghc-8.6.5/semantic-0.7.0.0/t/parse-examples/test/semantic-0.7.0.0-parse-examples.log`.

**Comment by exterm** [comment]
[semantic-0.7.0.0-parse-examples.log](https://github.com/github/semantic/files/3618276/semantic-0.7.0.0-parse-examples.log)

**Comment by robrix** [comment]
For future reference the thing where `new-test` requires an explicit `--enable-tests` is due to the specific version of the `network` package that we depend on (????).

**Comment by robrix** [comment]
Can repro the test failure too.

**Comment by patrickt** [comment]
I can’t reproduce this 🤔

**Comment by robrix** [comment]
@patrickt: Which part?
