### ISSUE TITLE
Reenable Java assignment.

### ISSUE THREAD

**Issue by patrickt** [github/semantic#255]
In #247, which we wanted to land so as to push out a new `semantic` to upstream services, we disabled Java assignment, reasoning that Java is not yet an officially supported language and that it wasn’t worth holding up the whole enterprise to fix assignment changes from upstream parser changes. We should fix said assignment changes and add it back to `semantic.cabal`.

**Comment by robrix** [comment]
We’ve got support for tagging using the precise ASTs as of #293, which I think subsumes this.
