### ISSUE TITLE
Upgrade to latest tree-sitter-typescript grammar

### ISSUE THREAD

**Issue by patrickt** [github/semantic#256]
Code like this:

```
interface Workers {
  (callback: WorkerCallback): void;
}
```

changed in shape here: https://github.com/tree-sitter/tree-sitter-typescript/commit/c5144ebf699e359555820502aab048cb9d28d34d

**Comment by robrix** [comment]
@maxbrunsfeld mentioned he fixed the grammar which should probably take care of it.

**Comment by patrickt** [comment]
Changing this bug’s title since the original issue was spurious (due to a bug in #247) but it did result in a grammar change upstream.

**Comment by patrickt** [comment]
Fixed.

**Comment by robrix** [comment]
@patrickt: When was this fixed?
