### ISSUE TITLE
Copy `prj` from fused-effects-0.5 into internal effect handlers.

### ISSUE THREAD

**Issue by patrickt** [github/semantic#289]
Because https://github.com/fused-effects/fused-effects/pull/223 is coming down the line, I want to make sure that we have a navigation path forward for what we’ll do about `Interpose`. I’d prefer not to merge the above until we can be sure that we won’t break `semantic` too badly.

**Comment by robrix** [comment]
IMO these are orthogonal—we define our own `Control.Effect.Interpose` locally (which we can 🔥 at our leisure), and while `prj` is indeed coming from `fused-effects`, we can simply copy the old definition of the class in somewhere—it’ll work unchanged.
