### ISSUE TITLE
Parse error on typescript file

### ISSUE THREAD

**Issue by marcelosousa** [github/semantic#31]
On the following typescript file: 
```
export type NoInfer<T> = T & { [K in keyof T]: T[K] };
```

I'm getting the following error:
```
cabal new-run semantic -- parse minimal.ts
Up to date
[(Error)
12:08:07]  WARN minimal.ts:1:1-3:1: error: expected end of input nodes, but got ParseError
1: export type NoInfer<T> = T & { [K in keyof T]: T[K] };
   ^...

 task=parse github_request_id=- github_is_public=False path=minimal.ts language=TypeScript
```

This is a minimal example when I tried to parse the file https://github.com/palantir/tslint/blob/master/src/language/rule/abstractRule.ts

**Comment by patrickt** [comment]
Hi there! Thanks for the report. Errors of this form are bugs in the tree-sitter parser, so I’ve taken the liberty of moving this: https://github.com/tree-sitter/tree-sitter-typescript/issues/70
