### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by bdrodes** [github/semantic#321]
The docker image fails to build on mac using the following command issued from within the semantic home directory:

```
docker build . -t semantic
```

Fails on step 17 with the following message: 

```
Step 17/25 : RUN cabal new-configure semantic semantic-core
 ---> Running in e9fb8a7a733b
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: semantic-0.8.0.0 (user goal)
[__1] unknown package: semantic-tags (dependency of semantic)
[__1] fail (backjumping, conflict set: semantic, semantic-tags)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: semantic, semantic-tags
```

**Comment by patrickt** [comment]
Looks like the invocation of `cabal new-configure` is bad: it should contain all the relevant subprojects.

**Comment by tclem** [comment]
Should we even be calling `new-configure` in the dockerfile to begin with? Also, I think that [Dockerfile](https://github.com/github/semantic/blob/1034cd5e39e640bcea91feae04b76c397c1b1421/Dockerfile) is expecting that docker layer caching is going to help our build times (but it probably isn't).

**Comment by robrix** [comment]
1. Looks like we’re not passing it any flags there, so it’s kind of pointless.

2. We should probably use `v2-` instead of `new-` everywhere, because it’s forward-compatible, whereas `new-` could potentially change meaning over time.
