### ISSUE TITLE
Python tagging differs between à la carte & precise

### ISSUE THREAD

**Issue by robrix** [github/semantic#378]
Found by @tclem, IIRC when comparing the results for the parse-examples stuff.

We’d expect code comments to be present in à la carte tags (perhaps incorrectly), and for parse errors to prevent tagging with precise ASTs, but they should otherwise be the same.

**Comment by tclem** [comment]
I haven't opened a PR yet, but [here's the branch](https://github.com/github/semantic/compare/test-precise-parsing) that demonstrates some of the differences.

**Comment by tclem** [comment]
Sorted out the important differences in https://github.com/github/semantic/pull/417.
