### ISSUE TITLE
Docker build error, cabal returns 137

### ISSUE THREAD

**Issue by fenig** [github/semantic#387]
I'm trying to build a docker image on mac, with:

```
$ docker image build -t semantic:0.9 .
```

The build fails at step 14 with the cabal returning 137.

```
Step 14/19 : RUN cabal v2-update &&     cabal v2-configure --flags="release" &&     cabal v2-build semantic:exe:semantic
 ---> Running in 82d5454b2b5f
Config file path source is default config file.
Config file /root/.cabal/config not found.
Writing default configuration to /root/.cabal/config

...

Completed    charset-0.3.7.1 (all, legacy fallback)
Starting     QuickCheck-2.13.2 (lib)
Building     QuickCheck-2.13.2 (lib)
The command '/bin/sh -c cabal v2-update &&     cabal v2-configure --flags="release" &&     cabal v2-build semantic:exe:semantic' returned a non-zero code: 137
```

I couldn't find anything about cabal and error code 137. I tried reverting back to a commit that was supposed to have fixed a different docker build issue, but that one fails too. Am I missing something?

**Comment by tclem** [comment]
Exit code 137 is an out of memory error code on Linux. You might try to increase the memory available to Docker and then try again.

**Comment by patrickt** [comment]
Yup, this is an OOM. I'm going to close this, but please leave further comments if you keep encountering this issue given an appropriate amount of memory available to the build (ideally at least 8GB RAM).

**Comment by fenig** [comment]
Thanks! I gave docker 8GB and it finished building the image without further issues.
