### ISSUE TITLE
List available languages if --language arg is wrong

### ISSUE THREAD

**Issue by RasmusWL** [github/semantic#390]
For example, 

```
$ semantic graph --language python main.py
option --language: cannot parse value `python'

Usage: semantic graph ([--imports] | [--calls]) [--packages] ([--dot] | [--json]
                      | [--show]) (--language ARG [--root DIR]
                      [--exclude-dir DIR] PATH | FILES... | --stdin)
  Compute a graph for a directory or from a top-level entry point module
```

I immediately tried `python3` and then `Python3`, before I arrived at the magical `Python` :sparkles: 

Would be great if the CLI could list what values _are_ valid. Essentially these lines

https://github.com/github/semantic/blob/9764d4f79d3cd733df3b532b06bb48257a8f54b9/src/Data/Language.hs#L136-L150

**Comment by robrix** [comment]
Good call. I think `optparse-applicative` should make this pretty easy.
