### ISSUE TITLE
`semantic graph` language inference is broken

### ISSUE THREAD

**Issue by patrickt** [github/semantic#391]
As reported by @RasmusWL. I’m fairly sure that https://github.com/github/semantic/pull/355 caused this regression. It’s not critical, but we should fix it.

**Comment by robrix** [comment]
I think this might be an intentional consequence of #283; @tclem, can you verify?

**Comment by tclem** [comment]
I can't tell from the issue title/body what problem we're discussing. @patrickt can you sketch out a few more details describing the issue? What's broken? What did you expect to happen, what happened instead?

**Comment by patrickt** [comment]
@tclem Apologies! The issue here is that demonstrated in #390:

The user has to type
```
$ semantic graph --language Python main.py
```

when it seems like
```
$ semantic graph main.py
```

should suffice. Is this intentional?

**Comment by tclem** [comment]
Hasn't the `graph` command always required specifying a language? I think we took away the confusing `path:Lang` syntax, but graphing often involves an entire project directory of files (if `main.py` imports something we go look for it) and we don't do cross language analysis so you have to pick one to get started.

I think we could infer from the file extension as an enhancement for sure.

**Comment by patrickt** [comment]
This code path no longer exists.
