### ISSUE TITLE
The `>+>` operator would invoke left arg twice on the same data

### ISSUE THREAD

**Issue by Heimdell** [github/semantic#392]
https://github.com/github/semantic/blob/770268fbdb4ea920d1d4f40b2224430fa9d32f0e/src/Control/Rewriting.hs#L135

Wouldn't it be more effective to
```haskell
 a >+> b = (a >>> try b) <|> b 
```

This way, `a` is invoked once, where in the former case `a` would be invoked on the same data twice.

**Comment by patrickt** [comment]
Good catch!
