### ISSUE TITLE
Not able to run cabal-v2 build

### ISSUE THREAD

**Issue by sonumehta** [github/semantic#393]
I have installed cabal version – 2.4.1.0 and ghc version 8.6.5
I get the following error when I run this command(cabal v2-build) :

_cabal: Could not resolve dependencies:
[__0] trying: semantic-0.9.0.0 (user goal)
[__1] next goal: unix (dependency of semantic)
[__1] rejecting: unix-2.7.2.2 (library is not buildable in the current
environment, but it is required by semantic)
[__1] rejecting: unix-2.7.2.1, unix-2.7.2.0, unix-2.7.1.0, unix-2.7.0.1,
unix-2.7.0.0, unix-2.6.0.1, unix-2.6.0.0, unix-2.5.1.1, unix-2.5.1.0,
unix-2.5.0.0, unix-2.4.2.0, unix-2.4.1.0, unix-2.4.0.2, unix-2.4.0.1,
unix-2.4.0.0, unix-2.3.2.0, unix-2.3.1.0, unix-2.3.0.0, unix-2.2.0.0, unix-2.0
(conflict: semantic => unix^>=2.7.2.2)
[__1] fail (backjumping, conflict set: semantic, unix)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: semantic, unix_
 

(I am new to Haskell) It would be good if someone can guide me with initial installation steps.

**Comment by patrickt** [comment]
@sonumehta It looks like you’re trying to build on Windows; is that the case? Semantic is not (yet) buildable on Windows, though it should work under WSL. Docker is another option.

**Comment by sonumehta** [comment]
Thats right @patrickt . Thanks for the quick response. Can I get it running on Linux VM?

**Comment by patrickt** [comment]
@sonumehta Yes, it should work fine on a VM (as long as it is provisioned with enough RAM, at least 8GB), though please feel free to file other tickets if it doesn’t work for you. I’m going to close this out and make a note that we should document that it doesn’t build on Windows right now.
