### ISSUE TITLE
Parsing error in python with tests (on GitHub)

### ISSUE THREAD

**Issue by dannaf** [github/semantic#401]
On [this code viewed in GitHub](https://github.com/pypa/pip/blob/17075cc17fc4a9d37b826e09cbdb7ba52d8e3735/src/pip/_internal/main.py#L34) the mouse-over on the `stderr` portion of `sys.stderr.write(...` incorrectly identifies the function as being defined in [line 250](https://github.com/pypa/pip/blob/17075cc17fc4a9d37b826e09cbdb7ba52d8e3735/tests/lib/__init__.py#L250) of the `tests/lib/__init__.py` file of the same repository (`pypa/pip`), where it rather clearly is simply the normal `sys.stderr`, as imported [a few lines above](https://github.com/pypa/pip/blob/17075cc17fc4a9d37b826e09cbdb7ba52d8e3735/src/pip/_internal/main.py#L11) with `import sys`

Looks like either testing files throw off the parser or/and that there isn't a proper order of priorities when parsing multiple files, where in this case the `import` statement of the current file is the correct priority scope

**Comment by patrickt** [comment]
Hey there! Thanks for reporting this: it’s indeed a bug, and one we’d like to fix. This is, however, not an issue with `semantic` so much as it is our internal tooling that builds on the results that `semantic`’s `tags` mode provides. The relevant repository is not open-source, but I’ve forwarded this issue there. Thanks again!
