### ISSUE TITLE
-Werror is inconvenient for local builds

### ISSUE THREAD

**Issue by robrix** [github/semantic#422]
My goal with enabling `-Werror` in `cabal.project` for local builds was to make it harder to run into cases where the build passes locally but fails in CI because e.g. you’ve got warnings in some file that you haven’t touched recently and so you don’t see them. In practice, it’s just become a pain for any workflow using `cabal build` instead of e.g. `script/repl`, often necessary to e.g. iterate on `haskell-tree-sitter` stuff.

Thus, I kinda think we should remove the setting in `cabal.project` and only enable it in CI builds.

**Comment by robrix** [comment]
(This was biting @tclem the other day.)

**Comment by patrickt** [comment]
I use `cabal build` a lot and would love this. I think we can just do it by adding `--ghc-options=“-Werror”` to our invocation of `cabal configure` in haskell.yml.

**Comment by robrix** [comment]
Well, this isn’t going to be as easy as I’d hoped—[`cabal` uses `--ghc-options` flags passed on the CLI as options for the dependencies](https://github.com/haskell/cabal/issues/3883), and what do you know, some of them have warnings:

```
System/Random.hs:43:1: error: [-Wtabs, -Werror=tabs]
    Tab character found here, and in 74 further locations.
    Please use spaces instead.
   |
43 |         (
   | ^^^^^^^^
```
