### ISSUE TITLE
AST datatypes should live in semantic

### ISSUE THREAD

**Issue by robrix** [github/semantic#423]
It’s agonizing trying to work on anything in `semantic` that involves touching `haskell-tree-sitter`, not least because of the hackage releases eventually involved for each of the `tree-sitter*` packages.

Further to this, there’s the `cabal` bug with internal libraries that keeps breaking our local builds every so often; the general painfulness of submodules; we’re really not ready for a hackage release yet; and the weird situation where `semantic-source` is depended upon by `tree-sitter` so it can’t be listed in `cabal.project` and that makes changing _it_ harder.

All of this is only going to get worse as we support more languages, too.

Given all of that, I’m of the opinion that the AST datatypes should live in one or more `semantic` packages. This would mean that:

- the `tree-sitter-*` packages would basically just build the parsers & vend the `tree_sitter_foo` symbol;
- the `semantic-*` language packages will contain the ASTs; and
- we would move codegen and unmarshalling into a semantic package, probably `semantic-ast`.

Some knock-on effects:

- the `tree-sitter-*` packages would really only change when we wanted to bump to the latest versions of the parsers; hackage releases aren’t a huge deal in this case
- changing the AST types, instances, etc. would happen entirely in semantic
- we could iterate more easily on e.g. performance of stuff like unmarshalling (which we were doing a lot of recently)
- there’d be _zero_ internal libraries to worry about, solving that pain once and for all
- `semantic-source` could be part of the `cabal.project` again instead of living in a weird little universe all by itself and not being very easy to work on
- I could add `Traversable1` to `semantic-ast` and derive instances of it for our ASTs without having to release `semantic-ast` on hackage (which it is much too early for)

**Comment by robrix** [comment]
@patrickt points out that this could introduce costly rebuilds of ASTs.

In fairness, we already get those with `tree-sitter-*`, and it’s harder for us to iterate on improving those build times with the AST datatypes living elsewhere.

**Comment by robrix** [comment]
> this sounds like a good candidate for a spike with some profiling to verify what the increased hit to build times looks like, and how the ergonomics feel with additional internal packages

— @rewinfrey

💯, I couldn’t agree more ☝️

**Comment by robrix** [comment]
As a variation on this, we could move the entirety of the `haskell-tree-sitter` repo over here, too.

**Comment by robrix** [comment]
A more philosophical point: ASTs are our bread and butter, it’s _really weird_ that we don’t actually define any here.

**Comment by robrix** [comment]
FWIW it’s currently taking [~22min to build our dependencies](https://github.com/github/semantic/pull/426/checks?check_run_id=393607365#step:6:1) in no small part because of `tree-sitter*`. We’re rebuilding dependencies on every push now, so unless that changes, we actually _can’t_ slow things down significantly by just moving the ASTs from the dependencies into `semantic`.

**Comment by aymannadeem** [comment]
I can't speak to the performance trade-offs, but I can attest to the simplification this would introduce, in addition to overcoming the internal libraries pain, submodules etc. Structurally it makes sense for ast generation to live in `semantic-ast`. I think it's a bit weird we have CodeGen APIs in the same place as our FFI code, even though there's a dependency there.

**Comment by robrix** [comment]
![finn - algebraic](https://user-images.githubusercontent.com/59671/73698211-7a664d00-46ae-11ea-89ca-181fb9d23505.gif)
