### ISSUE TITLE
Rebuilding dependencies is extremely slow

### ISSUE THREAD

**Issue by robrix** [github/semantic#427]
We recently stopped caching built dependencies, which means that we’re now rebuilding them on every push. Unfortunately, this is quite slow, on the order of [22min](https://github.com/github/semantic/pull/426/checks?check_run_id=393607365#step:6:1), in no small part due to `tree-sitter*`.

We stopped caching them due to [some advice](https://github.com/actions/cache/pull/148#pullrequestreview-341559878) we received, and the points there are quite valid—copying in large caches isn’t particularly fast either. But as things stand, it’s making it harder to move quickly in this repo, since we have a bunch of slow-to-build dependencies. I also have concerns about the energy expenditure involved in building them anew every time.

**Comment by robrix** [comment]
I think my ideal would be for us to have some sort of cloud build going for dependencies where we can cache each separately by version and only copy in the ones we’re actually going to use to build `semantic` & its tests, but that sounds like a Project™ to say the least.

**Comment by patrickt** [comment]
I’m in favor of turning caching build dependencies back on, though admittedly it’s not kind to the CI servers. Waiting 25 minutes to discover your code failed in tests is just too painful 😞

**Comment by patrickt** [comment]
Beyond that, my only suggestion is that we lean very hard into [Bazel](https://bazel.build) and [rules_haskell](https://rules-haskell.readthedocs.io/en/latest/), which is a _lot_ of complexity (but with a pretty good payoff).

**Comment by patrickt** [comment]
Build times are back under 10 minutes. I’m calling this solved for now, though I’m still looking into Bazel.
