### ISSUE TITLE
Plan: divest from Assignment

### ISSUE THREAD

**Issue by patrickt** [github/semantic#438]
@tclem and I have been trying to figure out the best way to do the following:

- [ ] Disable `semantic graph` for now
- [ ] ~Move `semantic diff` into its own project~ Disable `semantic diff` for now
- [ ] Move assignment and alacarte ASTs into internal RPC service for TOC summaries only (yay build times)
- [ ] Delete all `Task` machinery relating to alacarte ASTs
- [ ] Mark items in the `README` as under-construction pending expansion of precise AST stuff.
- [ ] Make `semantic graph` CLI call into `semantic-scope-graph`
- [ ] Port `semantic diff` to precise ASTs
- [ ] Make internal RPC service use precise ASTs, delete alacarte ASTs

**Comment by robrix** [comment]
We may wish to disable `semantic diff` temporarily rather than blocking this on implementing diffing for precise ASTs.

**Comment by robrix** [comment]
cf https://github.com/tree-sitter/haskell-tree-sitter/issues/263

**Comment by patrickt** [comment]
This is done!
