### ISSUE TITLE
Enabling code navigation in Github

### ISSUE THREAD

**Issue by achamsanjeevakumar** [github/semantic#443]
Hi,

I see code navigation is provided in github.com, I would like to enable similar thing hosted by our company. can you guide how to do it.

**Comment by patrickt** [comment]
@achamsanjeevakumar Hi there. I’m afraid that code navigation is not supported for GitHub Enterprise at the moment. Though I can’t speak as to the timing of any future features, I’ve noted your feature request in our internal systems, and will inform you in this issue should this feature land. In the meantime, I’m going to close this.
