### ISSUE TITLE
Port getting-started guide.

### ISSUE THREAD

**Issue by patrickt** [github/semantic#46]
We have internal documentation that describes how to get up and running with semantic quickly. We should port it to the `docs/` folder.

**Comment by marcelo-sousa-sonarsource** [comment]
I think the ideal scenario is to provide a Docker image.

**Comment by tclem** [comment]
We do also publish docker images internally - that should get ported over along with project CI.

**Comment by robrix** [comment]
👍 to docker images, but wonder if that should be a separate issue. I.e. I think docs & docker images serve different needs.

**Comment by patrickt** [comment]
I think given the existence of `docs/examples.md`, and the fact that we’re publishing Docker images, this is safe to close.
