### ISSUE TITLE
Eta

### ISSUE THREAD

**Issue by ShalokShalom** [github/semantic#47]
According to your report here: https://github.com/github/semantic/blob/master/docs/why-haskell.md

Eta might help you with some of your concerns with the language. In particular, with error handling due to improved compiler messages, and obviously all the JVM related parts. 

http://eta-lang.org/

**Comment by fishtreesugar** [comment]
Eta [does not support](https://eta-lang.org/docs/faq#is-eta-compatible-ghc8) many advanced features in recent GHC version.

**Comment by ShalokShalom** [comment]
You could still use it in order to get sane compiler notifications in case you use 95% of the supported language.

**Comment by patrickt** [comment]
Regardless of Eta’s advantages (and it is a cool project), switching to the JVM isn’t feasible at this point in the project’s lifecycle for both implementation and operational reasons.

**Comment by ShalokShalom** [comment]
I am not talking about switching to Eta. If you guys just would ONCE read the text that the people write, it would be wildly appreciated. And that from a Github employee ^.^
