### ISSUE TITLE
Enable JSON-dumping of precise ASTs.

### ISSUE THREAD

**Issue by pplam** [github/semantic#471]
**Semantic version**: [0.7.0.0](https://github.com/github/semantic/releases/tag/0.7.0.0)
**Input file**: [EurekaServiceDiscovery.java](https://github.com/apache/dubbo/blob/master/dubbo-registry/dubbo-registry-eureka/src/main/java/org/apache/dubbo/registry/eureka/EurekaServiceDiscovery.java) of Apache dubbo
**Command**: `semantic parse --json EurekaServiceDiscovery.java`
**Error logs**: 
~~~
[01:12:42]  WAR{"trees":[{"tree":{"term":"Error","errorActual":"ParseError","errorCallStack":[{"startLine":159,"module":"Language.Java.Assignment","package":"semantic-0.7.0.0-inplace","site":"parseError","file":"src/Language/Java/Assignment.hs","startColumn":128,"endColumn":138}],"errorChildren":[],"errorExpected":[],"sourceRange":[0,7602],"sourceSpan":{"start":[1,1],"end":[188,51]}},"path":"EurekaServiceDiscovery.java","language":"Java"}]}
N EurekaServiceDiscovery.java:1:1-188:51: error: expected end of input nodes, but got ParseError
1: /*
   ^...

 task=parse github_request_id=- github_is_public=False path=EurekaServiceDiscovery.java language=Java
~~~

But `tree-sitter` works fine to parse this file. Maybe there are some bugs with semantic to parse Java, someone help me to fix this please!

**Comment by patrickt** [comment]
@pplam It looks like you passed `semantic parse --json`. Did you mean `semantic parse --java`? If that doesn’t work, try `semantic parse --java-mode=Precise`.

**Comment by pplam** [comment]
@patrickt I used the `--json` flag to get the `json` format output. Unfortunately, there is neither `--java` nor `--java-mode=Precise` flag here.

**Comment by patrickt** [comment]
Looks like there’s some issues we need to work out in tree-sitter-java. Precise parsing fails with

```
tree-sitter: unmarshal failure - "type 'ScopedIdentifier' expected a node 'name' but didn't get one”
```

**Comment by patrickt** [comment]
Tested this and it appears to work now with precise parsing (`--show` or `--sexpression`). Currently working on a patch to allow precise JSON decoding.

**Comment by patrickt** [comment]
Changing the name of this bug to reflect the missing pieces of the above use case.

**Comment by pplam** [comment]
OK, thanks @patrickt
