### ISSUE TITLE
Precise ASTs don’t support parse errors

### ISSUE THREAD

**Issue by patrickt** [github/semantic#481]
_Ported from https://github.com/tree-sitter/haskell-tree-sitter/issues/114_

tree-sitter can return parse errors in the tree, but we can’t represent those in the TH-generated AST datatypes. This probably calls for higher-kinded data, which also would solve #480.

**Comment by llelf** [comment]
But for the time being, is it possible to get anything more than `Left "expected … but got ERROR"`? Location?

**Comment by patrickt** [comment]
This should be fixed now, thanks to #486.
