### ISSUE TITLE
Update language-integration docs

### ISSUE THREAD

**Issue by patrickt** [github/semantic#489]
Now that we’re truly, honest-to-$DEITY transitioning away from Assignment, it’s probably time to update the `adding-new-languages.md` file with the new way of doing things, as many people’s filed issues reference having read that.

**Comment by patrickt** [comment]
This has been taken care of already.

**Comment by Razzeee** [comment]
It would be very cool to have a section that talks about what this means for a language.
If we do this for language X and it gets merged:
- Will github use it for highlighting?
- Will github enable jump to definition/reference?
- What else would this work enable?
