### ISSUE TITLE
Array Filter()expects parameter 1 to be array?

### ISSUE THREAD

**Issue by MikeSchuit** [github/semantic#510]
Hi I have encountered an issue on my website. The following PHP code snippet appears on my front end website displayed behind my layers. I am not a coder but can make changes to the php if necessary. Please can anyone assist?  
Error message:
Warning: array_filter() expects parameter 1 to be array, boolean given /home/gordonfrasier/public_html/wp-content/plugins/divi-overlays/divi-overlays.php on line 2617
The code:
		}
					
					if ( $display_in_posts == 'all' ) {
						
						$display_in_current = true;
						
Line 2617 ------------->			 $except_in_posts = array_filter( get_post_meta( $overlay_id, 'do_at_pagesexception_selected' ) );
						
						if ( isset ( $except_in_posts[0] ) ) {
							
							foreach( $except_in_posts[0] as $in_post => $the_id ) {
								
								if ( $the_id == $current_post_id ) {
									
									$display_in_current = false;
									
									break;
								}
							}
						}
					}

**Comment by tclem** [comment]
👋

From the description, this doesn't appear related to the semantic project so I'm going to close this out.

**Comment by patrickt** [comment]
Hi there, @MikeSchuit. This repository is for `semantic`, a programming language analysis tool, and as such isn’t an appropriate forum for general PHP questions. I recommend consulting the manual or support forum for the specific software your blog uses.

**Comment by MikeSchuit** [comment]
Apologies I new here. Will do Thank you.
