### ISSUE TITLE
semantic-php.cabal refers to non-existing LICENSE

### ISSUE THREAD

**Issue by p-alik** [github/semantic#511]
https://github.com/github/semantic/blob/8745cf88c5cc266036b462b03f9cadaffb7f03ed/semantic-php/semantic-php.cabal#L10

`cabal v2-build` complains
```
Configuring library for semantic-php-0.0.0.0..
Warning: The 'license-file' field refers to the file 'LICENSE' which does not
```

**Comment by patrickt** [comment]
This is fixed by #535.
