### ISSUE TITLE
python language: issue on github showing code navigation of instance variables

### ISSUE THREAD

**Issue by amaajemyfren** [github/semantic#531]
Hi,

#### Preamble and caveats

I do not know Haskell or how to use semantic - I just saw [here](https://help.github.com/en/github/managing-files-in-a-repository/navigating-code-on-github#about-navigating-code-on-github) that github uses semantic and so had an issue (really small issue and thought to raise it in case you could know how to fix it. Feel free to ignore this and close this issue if it does not make sense - or if it is an issue of how github has implemented it.

Also while I have read #57 and that may be where this is addressed but it is not clear to me.
#### The actual issue:

Take [this](https://github.com/python/cpython/blob/master/Lib/json/encoder.py) file. More specifically look [here](https://github.com/python/cpython/blob/799d7d61a91eb0ad3256ef9a45a90029cef93b7c/Lib/json/encoder.py#L147-L152)

These are instance variables being initialised in the class (within the dunder method __init__). As such they are the definitions of the variables.

e.g. take the definition `self.indent = indent` When you highlight it and click the first indent you get:
![image](https://user-images.githubusercontent.com/32741226/78589358-c7020c00-7848-11ea-8f00-4d9d7cf77f84.png)
All those `indent` references are functions in other files - completely unrelated to this indent. This is in fact the definition of the indent. More annoyingly the second indent comes from the method [__init__](https://github.com/python/cpython/blob/799d7d61a91eb0ad3256ef9a45a90029cef93b7c/Lib/json/encoder.py#L104-L106) and not where it suggests it comes from now:
![image](https://user-images.githubusercontent.com/32741226/78589682-4099fa00-7849-11ea-8144-9c73dfe05909.png)

Also the other variables above it (`self.skipkeys`, `self.ensure_ascii`, `self.check_circular`, self.allow_nan` and `self.sort_keys`) all do not have code navigations and they should. They are all the definitions and they should also refer to the __init__ method.

Thanks.

**Comment by patrickt** [comment]
Hi there. This is indeed a bug, one that semantic doesn't handle correctly right now; since this relates to a GitHub feature directly, I'm closing this and moving it to our internal repository tracking code navigation issues. Thank you for the report!
