### ISSUE TITLE
Graphing project directories from the CLI searches wrong directories

### ISSUE THREAD

**Issue by mihairaulea** [github/semantic#548]
Using a locally built version of semantic, I have run it against a couple of projects.

`
SEMANTIC_ASSIGNMENT_TIMEOUT=1000000 cabal v2-run semantic -- graph --show --language JavaScript /Users/user/projectA
`

`
SEMANTIC_ASSIGNMENT_TIMEOUT=1000000 cabal v2-run semantic -- graph --show --language JavaScript /Users/user/projectB
`
The run was very slow, but I understand this is due to semantic processing all dependencies. Halted the process, and ran it against a simple project with zero dependencies.

I was expecting a fresh run - I saw the output stated that semantic is processing tasks from the old runs:

`task=assign github_request_id=- github_is_public=False path=/Users/user/projectB/src/router/index.js language=JavaScript`

However, when running semantic against a single file and not a directory, I got instant results. This works well and returns immediately:

`cabal v2-run semantic -- graph --json --language JavaScript /Users/user/nodeExampleApp/index.js`

Does semantic have a task queue of some sort, and if so, how can I clear it? I did not find any interesting parameters in src/Semantic/Config.hs.

**Comment by patrickt** [comment]
Thanks for the report! This looks like something’s going wrong in walking dependency trees, I think. It may be related to @zhujinxuan’s patches for file path handling.

**Comment by patrickt** [comment]
(Also n.b. that this `graph` command is deprecated, and will eventually be replaced with the work in #535.)

**Comment by zhujinxuan** [comment]
I will have a look on this this weekend.

**Comment by patrickt** [comment]
This code path has been eliminated.
