### ISSUE TITLE
Fix parse-examples test suite

### ISSUE THREAD

**Issue by lahiguera** [github/semantic#549]
On commit `66103a1b999118660e36ecb3e24aa777a080429b`, when running `cabal v2-test`, some tests failed with the following output: [semantic-0.11.0.0-parse-examples.log](https://github.com/github/semantic/files/4602664/semantic-0.11.0.0-parse-examples.log)

The version of ghc is 8.8.2. The version of cabal is 3.0.0.0. The OS is macOS Catalina version 10.15.4.

**Comment by patrickt** [comment]
Yeah, the parse-examples tests need to be refreshed (we don’t run these in CI due to time constraints).

**Comment by lahiguera** [comment]
Got it. Thank you @patrickt. Maybe I can help with this, but I would need some guidance/studying since I'm just getting familiar with `semantic`.

By the way, also thank you for updating the title of the issue.
