### ISSUE TITLE
Re-enable Core

### ISSUE THREAD

**Issue by aymannadeem** [github/semantic#569]
#486 set out to change the Kinds of ASTs, but due to some unforeseen downstream impacts of doing so, decided to instead introduce an error functor, a solution to report parse errors in the interim. This changed ASTs. While tagging and other higher priority dependencies were updated, `Core` and related modules were elided in that PR. Upon merge, `semantic` will not compile any `Core` modules (they're temporarily commented out). Therefore we should [come back and re-enable these](https://github.com/github/semantic/pull/486/files/f2cf1cadfedbeb96268f807a805c8b1daf2250af#r437413178) once we've settled on adjusting the Kinds of ASTs.

**Comment by patrickt** [comment]
We’ve nixed the old formulation of `Core`, so this no longer applies.
