### ISSUE TITLE
Bazel: `recompile with -fPIC` errors on Linux

### ISSUE THREAD

**Issue by patrickt** [github/semantic#595]
My experiments [here](https://github.com/github/semantic/runs/851893981?check_suite_focus=true) ran into a continual issue:

```
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/external/stackage/attoparsec-0.13.2.4/_install/lib/libHSattoparsec-0.13.2.4.a(FastSet.o): requires unsupported dynamic reloc 11; recompile with -fPIC
```

(repeated thousands of times)

I have no idea what we have to do to fix this, though some googling appears to indicate this is a static/dynamic problem. If you have further insight, please drop a comment here 👀

**Comment by tclem** [comment]
Might be a thing in the base image with `ld`? We've got this in one of our base dockerfile (used to build semantic stuff internally):

```
# Buggy versions of ld.bfd fail to link some Haskell packages: https://sourceware.org/bugzilla/show_bug.cgi?id=17689.
# Gold is faster anyways and uses less RAM.
RUN update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.gold" 20 && \
    update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.bfd" 10
```

**Comment by dcreager** [comment]
I kept running into this on my Linux box when trying to test #579.  The best discussion I could find was at tweag/rules_haskell#429.  That suggested a few workarounds, none of which worked for me:

```
$ bazel build -c opt //semantic:exe
$ bazel build --force_pic //semantic:exe
$ bazel build -c opt --copt '-fPIC' //semantic:exe
```

We might have to enlist Tweag's help with this.

I also got a bunch of ["invalid byte sequence" errors](https://github.com/tweag/rules_haskell#hgetcontents-invalid-argument-invalid-byte-sequence), but that one was solvable — I'm on Arch, which uses vanilla glibc, which doesn't provide a `C.UTF-8` locale, which `rules_haskell` wants to use as the reproducible locale when building.  Debian/Ubuntu (which I think we're using for our base Docker images) patches glibc to provide that locale, so we shouldn't (and I think you didn't?) run into that error here.

**Comment by aherrmann** [comment]
@patrickt That looks like an error we encountered on Bazel CI recently: https://github.com/tweag/rules_haskell/issues/1349
The issue occurred on Ubuntu 18.04 with GHC 8.8 which seems to match your setup.
A fix is available here: https://github.com/tweag/rules_haskell/pull/1388

**Comment by dcreager** [comment]
Woohoo! :tada: @aherrmann I can confirm that fixes the Linux builds for us: https://github.com/github/semantic/compare/bazel-linux-fixes
