### ISSUE TITLE
Bazel in CI reporting errors

### ISSUE THREAD

**Issue by rewinfrey** [github/semantic#619]
In https://github.com/github/semantic/pull/618, @patrickt and I ran into some issues getting Bazel to build `semantic` correctly in CI. Locally, bazel builds are still working, but there is something specific about the CI setup that is creating an issue. For now bazel builds are disabled in CI for `semantic`, but it would be ideal to troubleshoot and fix the CI bazel builds.

**Comment by patrickt** [comment]
This is fixed.
