### ISSUE TITLE
Publish semantic docker image

### ISSUE THREAD

**Issue by robrix** [github/semantic#62]
Per @tclem’s [post](https://github.com/github/semantic/issues/46#issuecomment-498750790):

> We do also publish docker images internally - that should get ported over along with project CI.

**Comment by dcreager** [comment]
I can take this one, I've got the keys to the existing Docker hub account

**Comment by tclem** [comment]
Publishing is a manual process, but we've got a [docker image now](https://github.com/github/semantic/packages/11609):

``` bash
docker pull docker.pkg.github.com/github/semantic/semantic
```

**Comment by ChrisPenner** [comment]
Is the docker image published publicly anywhere? It'd be handy for folks to use :) 

```bash
$ docker pull docker.pkg.github.com/github/semantic/semantic
Using default tag: latest
Error response from daemon: Get https://docker.pkg.github.com/v2/github/semantic/semantic/manifests/latest: no basic auth credentials
```

**Comment by tclem** [comment]
@ChrisPenner you'll need to authenticate (`docker login`) to access docker packages hosted on github.com - check out the [docs here](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages).
