### ISSUE TITLE
Remove the install via homebrew from the bootstrap?

### ISSUE THREAD

**Issue by philderbeast** [github/semantic#628]
I see from their docs that the binary installer is the recommended way to install bazel on mac.

https://docs.bazel.build/versions/master/install-os-x.html

Would it be possible to remove the install via homebrew from the bootstrap?

https://github.com/github/semantic/blob/aca39e86683cf09071fc884313d7ec676f4c2c4b/script/bootstrap-bazel#L6

**Comment by patrickt** [comment]
At GitHub, the convention for software installed through `script/bootstrap` scripts is to use Homebrew. Nothing in the documentation or the Homebrew formula suggests to me that there’s a substantiative difference between the options, and said formula seems like it’s up to date, so I think it’s most appropriate to stick to our conventions here.

**Comment by philderbeast** [comment]
I was unaware of the github convention. Good to know. Thanks for the explanation.
