### ISSUE TITLE
GitHub Enterprise Support

### ISSUE THREAD

**Issue by slang25** [github/semantic#631]
I've seen a couple of comments regarding semantic code support suggesting there is no current plans to bring it to GitHub Enterprise.

Is there a place to track user suggestions like this? It might be good to keep an issue open here to gauge demand for it.

**Comment by patrickt** [comment]
Thanks for filing this! We’ve gotten a lot of requests for this, so we're tracking this in an internal private repository. I’ll link to this therein.

**Comment by dcreager** [comment]
Here is the internal roadmap issue tracking this request: https://github.com/github/roadmap-internal/issues/77
