### ISSUE TITLE
Semantic as a library

### ISSUE THREAD

**Issue by dciug** [github/semantic#645]
Is there any way to use Semantic as a library? Right now, I'm using semantic as an external executable, and capturing the output using readProcess and https://hackage.haskell.org/package/semantic-source.

Thanks.

**Comment by patrickt** [comment]
Though I think your solution is pretty good, there’s nothing stopping you from using this as a library (except the fact that we haven’t uploaded this to Hackage). I would probably start by looking at [`Semantic.Task`](https://github.com/github/semantic/blob/master/semantic/src/Semantic/Task.hs). I’m going to close this now, but feel free to leave comments if you run into trouble.
