### ISSUE TITLE
👋 @jgimenez 🙂  To answer your main question:

### ISSUE THREAD

**Issue by 123MwanjeMike** [github/semantic#658]
👋 @jgimenez 🙂  To answer your main question:

> It's not clear to me if there's a way to move the users to the new app, so they don't need to re-authenticate (I guess there is not, but I think should be indicated)

IIUC, no, this isn't possible. The new app is essentially a distinct installation, so it's access must be authenticated by the user. 

> It's not clear to me whether I should delete the old OAuth app. It's confusing to me, because it says we should encourage users to de-authorize the old app, but if the old app is no longer in use, it would make more sense to me to delete the app, so its credentials can not be abused in any way and all authorizations are revoked.

I think this was originally written implying that some users might still be using the old app. If all your users have transitioned off the old app, or if you're happy to delete the old app even though it might still have active users, then deleting the app makes sense 👍

We can definitely update the doc to be more clear about both these points. I'll open this issue up for anyone to take on 🙂

_Originally posted by @lucascosti in https://github.com/github/docs/issues/1236#issuecomment-742257828_

**Comment by Elpasto28** [comment]
> 👋 @jgimenez 🙂 Para responder a su pregunta principal:
> 
> > No tengo claro si hay una forma de mover a los usuarios a la nueva aplicación, por lo que no necesitan volver a autenticarse (supongo que no, pero creo que debería indicarse)
> 
> IIUC, no, esto no es posible. La nueva aplicación es esencialmente una instalación distinta, por lo que su acceso debe ser autenticado por el usuario.
> 
> > No me queda claro si debería eliminar la antigua aplicación OAuth. Es confuso para mí, porque dice que deberíamos alentar a los usuarios a desautorizar la aplicación anterior, pero si la aplicación anterior ya no está en uso, tendría más sentido para mí eliminar la aplicación, por lo que no se puede abusar de sus credenciales. de cualquier forma y se revocan todas las autorizaciones.
> 
> Creo que esto se escribió originalmente dando a entender que algunos usuarios podrían seguir usando la aplicación anterior. Si todos sus usuarios han abandonado la aplicación anterior, o si está contento de eliminar la aplicación anterior a pesar de que todavía puede tener usuarios activos, entonces eliminar la aplicación tiene sentido.👍
> 
> Definitivamente podemos actualizar el documento para que sea más claro sobre estos dos puntos. Abriré este problema para que cualquiera lo aborde.🙂
> 
> _Publicado originalmente por @lucascosti en [github / docs # 1236 (comentario)](https://github.com/github/docs/issues/1236#issuecomment-742257828)_
