### ISSUE TITLE
Set us up some CI

### ISSUE THREAD

**Issue by dcreager** [github/semantic#7]
We should set up some CI to run the test suite for each candidate PR.

(To be clear, we were doing this before!  We should just start doing it _again_ now that the library is open sourced.)

**Comment by gjedeer** [comment]
Since you're providing a Docker image too, perhaps the CI should also try `docker build`ing the image (since, as of now, it fails)

**Comment by patrickt** [comment]
Both of these issues should be fixed with #110.
