### ISSUE TITLE
Migrate responsibility for AST schemas to the grammars

### ISSUE THREAD

**Issue by robrix** [github/semantic#72]
tree-sitter grammars don’t impose (m)any restrictions on the shape of ASTs, which in practice means that if we need to have the assurance that an if statement is consistently shaped the way we think an if statement should be, we have to parse the raw parse trees into our more precisely shaped syntax trees, a process which we call “assignment” (or “term assignment,” by analogy with “type assignment,” or inference).

By contrast, if we wrote the parsers using idiomatic Haskell combinators, we’d map the characters/tokens directly onto the final trees in one step, e.g.:

```haskell
Statement.If <$ keyword "if" <*> expr <* keyword "then" <*> expr <* keyword "else" <*> (expr <|> emptyTerm)
```

If we move the responsibility for adhering to and validating schemas into the grammars, then we can potentially make three simplifications:

1. Parsing would produce the final trees, allowing us to replace the complicated assignment step with a simple deserialization;
2. A machine-parseable format for the schemas would enable us to generate the datatypes representing syntax e.g. using `TemplateHaskell`, just like we currently do to generate the grammar datatypes; and
3. Eventually, parsing of blobs into syntax trees and persistence of said trees could be performed in a service completely decoupled from `semantic`, allowing us (and other services) to consume trees instead of blobs as inputs.

Finally, it would additionally benefit other users of the parsers since they too would get the benefit of getting consistent, predictable, well-formed syntax trees back, e.g. in syntax highlighting you want to consistently use the same colour to highlight “the same” pieces of syntax across different languages.

**Comment by robrix** [comment]
@maxbrunsfeld & @aymannadeem have been working on this in `tree-sitter` & `haskell-tree-sitter` respectively.

**Comment by robrix** [comment]
This will eventually supersede all [assignment issues](https://github.com/github/semantic/labels/assignment).

**Comment by patrickt** [comment]
I’d say this seems done.
