### ISSUE TITLE
how to build and install?

### ISSUE THREAD

**Issue by BlankRain** [github/semantic#92]
➜  semantic git:(master) cabal install
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: semantic-0.6.0 (user goal)
[__1] unknown package: tree-sitter-typescript (dependency of semantic)
[__1] fail (backjumping, conflict set: semantic, tree-sitter-typescript)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: semantic, tree-sitter-typescript

**Comment by patrickt** [comment]
Hi! The [Development](https://github.com/github/semantic#development) section of the README specifies that you should use `cabal new-build` (or `cabal new-install`), rather than installing it in the legacy style with `cabal build`.

I’m going to close this now, but if you run into more difficulties please let us know.

**Comment by BlankRain** [comment]
thank you @patrickt

**Comment by Congee** [comment]
same error with `cabal new-build`. My cacal-install has version 3.1.0.0

using HEAD 9764d4f79d3cd733df3b532b06bb48257a8f54b9

**Comment by patrickt** [comment]
@Congee Have you tried a `cabal update` before running the build? The `tree-sitter-typescript` package is on Hackage, so it should be visible if you’ve got an up-to-date package index.

**Comment by Congee** [comment]
@patrickt that was a prompt reply. I did with no luck. What else can I do to help solve or debug this issue?
<details><summary>log</summary>
<p>

```bash
~/dev/haskell/semantic$ git show --oneline
9764d4f79 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #386 from github/warnings

~/dev/haskell/semantic$ script/bootstrap
Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2019-11-20T21:20:21Z'
~/dev/haskell/semantic$ cabal new-update
Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2019-11-20T21:20:21Z'
~/dev/haskell/semantic$ cabal new-build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: fused-syntax-0.0.0.0 (user goal)
[__1] next goal: base (dependency of fused-syntax)
[__1] rejecting: base-4.13.0.0/installed-4.1... (conflict: fused-syntax =>
base^>=4.12.0.0)
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: base, fused-syntax)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, fused-syntax

~/dev/haskell/semantic$ cabal update
Downloading the latest package list from hackage.haskell.org
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2019-11-20T21:20:21Z'
~/dev/haskell/semantic$ cabal new-build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: fused-syntax-0.0.0.0 (user goal)
[__1] next goal: base (dependency of fused-syntax)
[__1] rejecting: base-4.13.0.0/installed-4.1... (conflict: fused-syntax =>
base^>=4.12.0.0)
[__1] rejecting: base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__1] fail (backjumping, conflict set: base, fused-syntax)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, fused-syntax

~/dev/haskell/semantic$ cabal --version
cabal-install version 3.1.0.0
compiled using version 3.1.0.0 of the Cabal library
~/dev/haskell/semantic$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.1
~/dev/haskell/semantic$
```
</p>
</details>

**Comment by Congee** [comment]
Is it because my ghc is too new? I'll try 8.6.5

**Comment by Congee** [comment]
This line is interesting.
> [__1] rejecting: base-4.13.0.0/installed-4.1... (conflict: fused-syntax =>
base^>=4.12.0.0)

It starts building after I switched to 8.6.5
