### ISSUE TITLE
cabal new-install fails to copy tree-sitter header files when packaging haskell-tree-sitter submodule

### ISSUE THREAD

**Issue by shapr** [github/semantic#96]
This is probably low priority?

When running "cabal new-install exe:semantic" after carefully following the directions at https://github.com/github/semantic#development
The build for tree-sitter fails in a way I couldn't easily figure out.

new-build, new-run, and new-test all succeed though.

**Comment by robrix** [comment]
Thanks for filing! Could you please paste the failure message(s) you were seeing, if any?

**Comment by shapr** [comment]
Oh, I bet this is fixed by #95 ! I'll check that first.

**Comment by patrickt** [comment]
I think we saw this internally — @donokuda and @tclem ran into this setting up from a fresh development environment. I haven’t been able to repro so I haven’t the faintest what’s going on.

**Comment by shapr** [comment]
cargo can't build a HEAD clone of the tree-sitter repo, I'm almost certain that's the problem.

Even so, here's the error from cabal:

`/usr/bin/gcc -fno-stack-protector '-fuse-ld=gold' /tmp/24299-4.c -o /tmp/24299-5 '-D__GLASGOW_HASKELL__=806' '-Dlinux_BUILD_OS=1' '-Dx86_64_BUILD_ARCH=1' '-Dlinux_HOST_OS=1' '-Dx86_64_HOST_ARCH=1' -Idi
st/build/autogen -Idist/build/includes -Idist/build/vendor/tree-sitter/lib/include -Idist/build/vendor/tree-sitter/lib/src -Idist/build/vendor/tree-sitter/lib/utf8proc -I./includes -I./vendor/tree-sitt
er/lib/include -I./vendor/tree-sitter/lib/src -I./vendor/tree-sitter/lib/utf8proc -I. '-std=c99' -Os -I/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/unix-2.7.2.2/include -I/home/shae/.ghcup/ghc/8.6.5/lib/g
hc-8.6.5/time-1.8.0.2/include -I/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/bytestring-0.10.8.2/include -I/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/base-4.12.0.0/include -I/home/shae/.ghcup/ghc/8.6.5/lib
/ghc-8.6.5/integer-gmp-1.0.2.0/include -I/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/include '-std=c99' -Os -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/template-haskell-2.14.0.0 -L/home/shae/.cabal/store
/ghc-8.6.5/split-0.2.3.3-b9ef85396c92f073ce3063cf44bf2a2b6d2a1c68e9fa476d43e7597544ef642e/lib -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/pretty-1.1.3.6 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/ghc-
boot-th-8.6.5 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/directory-1.3.3.0 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/unix-2.7.2.2 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/time-1.8.0.2 -L/home/sha
e/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/filepath-1.4.2.1 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/bytestring-0.10.8.2 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/deepseq-1.4.4.0 -L/home/shae/.ghcup/ghc/8.6
.5/lib/ghc-8.6.5/array-0.5.3.0 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/base-4.12.0.0 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/integer-gmp-1.0.2.0 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/ghc-
prim-0.5.3 -L/home/shae/.ghcup/ghc/8.6.5/lib/ghc-8.6.5/rts
/usr/bin/gcc returned ExitFailure 1 with error message:                  
/tmp/24299-4.c:1:10: fatal error: tree_sitter_ptr.h: No such file or directory
#include "tree_sitter_ptr.h"`

**Comment by shapr** [comment]
A bit more investigation says this issue is not related to semantic, but instead haskell-tree-sitter
I'll close this issue and create a new report in the correct repo, sorry!

**Comment by fredefox** [comment]
@shapr, I'm seeing this as well. Did you manage to fix it?

**Comment by robrix** [comment]
I can’t repro, but I have a pretty strong hunch that I know how to fix it just the same. Will attempt to later today.

**Comment by robrix** [comment]
I _think_ checking out #95 and then bumping your `vendor/haskell-tree-sitter` submodule to point at https://github.com/tree-sitter/haskell-tree-sitter/pull/119 should resolve this. Can someone confirm?

**Comment by shapr** [comment]
I'm using ubuntu 19.04 with ghcup for installing ghc 8.6.5 and cabal, and using "cabal new-update && cabal new-install exe:semantic"

I grabbed #95 and then in the haskell-tree-sitter submodule I also checked out https://github.com/tree-sitter/haskell-tree-sitter/pull/119 and I get a different error message this time:

/home/shae/.ghcup/bin/ghc -c -fPIC -odir dist/build -Idist/build/autogen -Idist/build/global-autogen -Idist/build -Ivendor/tree-sitter/lib/include -Ivendor/tree-sitter/lib/src -Ivendor/tree-sitter/lib/
utf8proc -Idist/build/vendor/tree-sitter/lib/include -Idist/build/vendor/tree-sitter/lib/src -Idist/build/vendor/tree-sitter/lib/utf8proc -optc-O2 '-optc-std=c99' -optc-Os -hide-all-packages -no-user-p
ackage-db -package-db /home/shae/.ca/home/shae/.ghcup/bin/ghc -c -fPIC -odir dist/build -Idist/build/autogen -Idist/build/global-autogen -Idist/build -Ivendor/tree-sitter/lib/include -Ivendor/tree-sitter/lib/src -Ivendor/tree-sitter/lib/
utf8proc -Idist/build/vendor/tree-sitter/lib/include -Idist/build/vendor/tree-sitter/lib/src -Idist/build/vendor/tree-sitter/lib/utf8proc -optc-O2 '-optc-std=c99' -optc-Os -hide-all-packages -no-user-p
ackage-db -package-db /home/shae/.cabal/store/ghc-8.6.5/package.db -package-db dist/package.conf.inplace -package-id aeson-1.4.3.0-451e70a73c1f4107cb27048ea2f7573fb9d4e27354de3309e240f114d242e7ca -pack
age-id base-4.12.0.0 -package-id bytestring-0.10.8.2 -package-id directory-1.3.3.0 -package-id filepath-1.4.2.1 -package-id fused-effects-0.4.0.0-046ae9a6ab0204f32f75108f2af7d1cfa0aa4f1137c2ca27a18b014
bb871f5f8 -package-id hedgehog-1.0-c17d05956e798bfc7136988a88c302127dbb611c856930dc33f0fdac4451b407 -package-id split-0.2.3.3-b9ef85396c92f073ce3063cf44bf2a2b6d2a1c68e9fa476d43e7597544ef642e -package-i
d template-haskell-2.14.0.0 -package-id text-1.2.3.1 -package-id unordered-containers-0.2.10.0-65417f03bb6cbbddcf19a16c036e5135e86c8f96f360544d3beb64aa32a447cb src/bridge.c -hide-all-packages -O2 -j12 
'+RTS' -A128m -n4m -RTS -O2 -j12 '+RTS' -A128m -n4m -RTS                                                                                                                                                 
                                                                                                                                                                                                         
src/bridge.c:1:10: error:                                                                                                                                                                                
     fatal error: tree_sitter/api.h: No such file or directory                                                                                                                                           
     #include "tree_sitter/api.h" bal/store/ghc-8.6.5/package.db -package-db dist/package.conf.inplace -package-id aeson-1.4.3.0-451e70a73c1f4107cb27048ea2f7573fb9d4e27354de3309e240f114d242e7ca -pack
age-id base-4.12.0.0 -package-id bytestring-0.10.8.2 -package-id directory-1.3.3.0 -package-id filepath-1.4.2.1 -package-id fused-effects-0.4.0.0-046ae9a6ab0204f32f75108f2af7d1cfa0aa4f1137c2ca27a18b014
bb871f5f8 -package-id hedgehog-1.0-c17d05956e798bfc7136988a88c302127dbb611c856930dc33f0fdac4451b407 -package-id split-0.2.3.3-b9ef85396c92f073ce3063cf44bf2a2b6d2a1c68e9fa476d43e7597544ef642e -package-i
d template-haskell-2.14.0.0 -package-id text-1.2.3.1 -package-id unordered-containers-0.2.10.0-65417f03bb6cbbddcf19a16c036e5135e86c8f96f360544d3beb64aa32a447cb src/bridge.c -hide-all-packages -O2 -j12 
'+RTS' -A128m -n4m -RTS -O2 -j12 '+RTS' -A128m -n4m -RTS                                                                                                                                                 
                                                                                                                                                                                                         
src/bridge.c:1:10: error:                                                                                                                                                                                
     fatal error: tree_sitter/api.h: No such file or directory                                                                                                                                           
     #include "tree_sitter/api.h"

**Comment by patrickt** [comment]
This appears to be fixed for me. @shapr, can you confirm it works with the latest HEAD?

**Comment by patrickt** [comment]
This should be fixed by #110.

**Comment by shapr** [comment]
I blew away my clone and started from a pristine checkout.
I then checked out #110 linked above and it worked great!

As long as I carefully follow the "development" instructions, I'm now able to `cabal new-install exe:semantic` ! Thanks for all the fixes!

**Comment by shapr** [comment]
fixed!

**Comment by robrix** [comment]
Thanks for the confirmation @shapr!
